### ISSUE TITLE
Suggested (or rather possible) typo.

### ISSUE THREAD

**Issue by OkomoJacob** [bensonkenduiywo/intro2geostats#1]
Hello Dr. Benson as a young developer, I got impressed way too much with the open source contribution you're into here, Cheers!. Occasionally, as human we might slightly miss a thing in our work. [Kindly check here and fix](https://bensonkenduiywo.github.io/intro2geostats/index.html). ...geostatistics deals with the analysis of random fields Z(s), where `Z` is a random variable and `x` the non-random spatial index. I suppose the `x` could be `s` instead. Kindly review and close the issue when fixed. Thank you.
-Your student, Geostatistics.

**Comment by bensonkenduiywo** [comment]
--Thanks...typo fixed

**Comment by OkomoJacob** [comment]
--Welcome teacher, issue successfully closed.
